"""Tag model for media tags."""

from enum import Enum
from typing import Optional

from sqlalchemy import Float, ForeignKey, Index, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.models import Base, UUIDMixin, TimestampMixin


class TagSource(str, Enum):
    """Source of the tag."""

    AI = "ai"  # Generated by AI
    MANUAL = "manual"  # Added by user


class Tag(Base, UUIDMixin, TimestampMixin):
    """Tag for media item (AI or manual)."""

    __tablename__ = "tag"

    # Composite index for efficient queries
    __table_args__ = (
        Index("ix_tag_media_name", "media_id", "tag_name"),
    )

    media_id: Mapped[UUID] = mapped_column(
        ForeignKey("media.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    tag_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,  # For searching by tag
    )
    confidence: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        comment="AI confidence score (0-1)",
    )
    source: Mapped[TagSource] = mapped_column(
        String(10),
        default=TagSource.AI,
        nullable=False,
    )

    # Relationships
    media: Mapped["Media"] = relationship("Media", back_populates="tags")

    def __repr__(self) -> str:
        return f"<Tag {self.tag_name} ({self.source})>"
